CREATE DATABASE LAYLOIHOI_DB
CREATE TABLE KHACHHANG(
    MAKH INT PRIMARY KEY,
    TENKH VARCHAR(30),
    DIACHI VARCHAR(50),
    SODT CHAR(11)
)
CREATE TABLE PHONG(
    MAPHONG INT PRIMARY KEY,
    LOAIPHONG VARCHAR(20),
    SOKHACHTOIDA INT,
    GIAPHONG DECIMAL(6,3),
    MOTA VARCHAR(25) 
)
CREATE TABLE DATPHONG(
    MADATPHONG INT PRIMARY KEY,
    MAPHONG INT,
    MAKH INT,
    NGAYDAT DATE,
    GIOBATDAU TIME,
    GIOKETTHUC TIME,
    TIENDATCOC DECIMAL(6,3),
    GHICHU VARCHAR(255),
    TRANGTHAIDAT VARCHAR(30),
    FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)
INSERT INTO 'phong' ('MAPHONG','LOAIPHONG',) VALUES (1,'LOAI1',20)


SELECT MADATPHONG, MADV, SOLUONG
FROM CHITIETSUDUNGDICHVU
WHERE SOLUONG BETWEEN 4 AND 9

UPDATE PHONG
SET GIAPHONG = GIAPHONG + 10
WHERE SOKHACHTOIDA > 10

DELETE 
FROM DATPHONG
WHERE TRANGTHAIDAT = 'DAHUY'

SELECT TENKH
FROM KHACHHANG
WHERE TENKH LIKE '[HNM]%' AND LEN(TENKH) <= 20

SELECT DISTINCT TENKH
FROM KHACHHANG

SELECT TENKH 
FROM KHACHHANG
GROUP BY TENKH

SELECT MADV, TENDV, DONVITINH, DONGIA
FROM DICHVUDIKEM
WHERE (DONVITINH LIKE 'LON' AND DONGIA > 10) OR (DONVITINH LIKE 'CAI' AND DONGIA < 5)

SELECT DP.MADATPHONG, P.MAPHONG,
FROM DATPHONG DP
JOIN KHACHHANG KH
ON DP.MAKH = KH.MAKH
JOIN PHONG P
ON DP.MAPHONG = P.MAPHONG
JOIN CHITIETSUDUNG CT 
ON DP.MADATPHONG = CT.MADATPHONG
JOIN DICHVUDIKEM DV 
ON CT.MADV = DV.MADV


CREATE DATABASE QL_DIEMTHI

CREATE TABLE SINHVIEN(

    MASV INT PRIMARY KEY,

    GIOITINH VARCHAR(10),

    TUOI INT,

    NGANHHOC VARCHAR(50)

)

CREATE TABLE NGANHHOC(

    MANGANHHOC INT PRIMARY KEY,

    TENNGANHHOC VARCHAR(50),

    FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    FOREIGN KEY (MANGANHHOC) REFERENCES NGANHHOC(MANGANHHOC)
)

CREATE TABLE MONHOC(

    MAMONHOC INT PRIMARY KEY,

    TENMONHOC VARCHAR(50),

    SOTINCHI INT,
    FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)
   )
   SELECT MH.TENMONHOC
   FROM MONHOC MH
   JOIN SINHVIEN SV 
   ON MH.MASV = SV.MASV
   WHERE SV.MASV = 'uni123'

   SELECT COUNT(SV.MASV)
   FROM SINHVIEN SV 
   JOIN MONHOC MH 
   ON MH.MASV = SV.MASV
   WHERE MH.SOTINCHI = 200